### ISSUE TITLE
abs(::SFloat64) not defined

### ISSUE THREAD

**Issue by felixcremer** [ffevotte/StochasticArithmetic.jl#1]
If I try to use this package with my algorithm, I fail because abs(::SFloat64) is not defined:
```julia
julia> @reliable_digits abs(SFloat64(-.009))
ERROR: MethodError: no method matching abs(::SFloat64)
Closest candidates are:
  abs(::Bool) at bool.jl:91
  abs(::Float16) at float.jl:520
  abs(::Float32) at float.jl:521
```
It would be nice, if this would work.

**Comment by ffevotte** [comment]
Thanks for this issue.

I added support for `abs` in branch [issue1](/ffevotte/StochasticArithmetic.jl/tree/issue1). Could you please test it and report back?

Please note that this package is still very much a work in progress, and has not (yet) been used in real world applications. A lot of common functions like this could be missing. Do not hesitate to list every function you are missing. I'm sorry if this process is too cumbersome; I'll try to add support for more functions as I go along with further developments of this package.

**Comment by felixcremer** [comment]
Thanks for fixing this. 
This simple use case now works. 
I am going to test your package further next week.

**Comment by ffevotte** [comment]
Thanks for the feed-back. Don't hesitate to ask for more, should the need arise.

**Comment by felixcremer** [comment]
You should merge the issue1 branch into master.

**Comment by ffevotte** [comment]
Done in #2, thanks!
